export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const SET_JWT_TOKEN = "SET_JWT_TOKEN";

export const CHECK_IF_USER_EXISTS = "CHECK_IF_USER_EXISTS";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const RESEND_EMAIL = "RESEND_EMAIL";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT_COMPLETED_SETUP = "GET_PROJECT_COMPLETED_SETUP";

export const GET_STRIPE_CHECKOUT_SESSION = "GET_STRIPE_CHECKOUT_SESSION";
